parameters:
  AksClusterName: 
  AksResourceGroupName: 
  AppGatewayName:
  AppGatewayResourceGroup: 
  AzureServiceConnection: 
  Environment: 
  GrafanaBaseUri: 
  GrafanaAdminPassword: 
  GrafanaAdminUsername:
  HelmClientVersion: 
  HelmChartVersion: 
  KeyVaultName: 
  KubectlVersion: 
  ResourceGroupLocation: 
  SubscriptionId: 
  TemplateSecrets: {}

jobs:
- deployment: DeployTo_${{ parameters.Environment }}
  environment: ${{ parameters.Environment }}
  pool:
    name: 'DAS - Continuous Integration'
    ## Linux agent required to ensure the 'kubectl cp' in Copy-FileToContainer.ps1 functions as expected
    demands: Agent.OS -equals Linux
  variables:
  - name: KubernetesNamespace
    value: monitoring
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
          path: 'das-grafana/'
        - task: KubectlInstaller@0
          displayName: 'Install Kubectl ${{ parameters.KubectlVersion }}'
          inputs:
            kubectlVersion: ${{ parameters.KubectlVersion }}
        - task: HelmInstaller@1
          displayName: 'Install Helm ${{ parameters.HelmClientVersion }}'
          inputs:
            helmVersionToInstall: ${{ parameters.HelmClientVersion }}
        - task: HelmDeploy@0
          displayName: 'Check application-gateway-ingress deployed'
          inputs:
            azureSubscription: '${{ parameters.AzureServiceConnection }}'
            azureResourceGroup: '${{ parameters.AksResourceGroupName }}'
            kubernetesCluster: '${{ parameters.AksClusterName }}'
            useClusterAdmin: true
            command: get
            namespace: default
            arguments: 'all application-gateway-ingress'
        - template: azure-pipelines-templates/deploy/step/arm-deploy.yml@das-platform-building-blocks
          parameters:
            Location: ${{ parameters.ResourceGroupLocation }}
            ParametersPath: $(Pipeline.Workspace)/das-grafana/azure/template.parameters.json
            ServiceConnection: ${{ parameters.AzureServiceConnection }}
            SubscriptionId: ${{ parameters.SubscriptionId }}
            TemplatePath: $(Pipeline.Workspace)/das-grafana/azure/template.json
            IsMultiRepoCheckout: true
            TemplateSecrets: ${{ parameters.TemplateSecrets }}
        - task: AzurePowerShell@5
          displayName: 'Azure PowerShell: Set StorageAccountKey variable'
          inputs:
            azureSubscription: ${{ parameters.AzureServiceConnection }}
            scriptType: inlineScript
            inline: |
              $Keys = Get-AzStorageAccountKey -ResourceGroupName $(RESOURCEGROUPNAME) -Name $(STORAGEACCOUNTNAME)
              Write-Output "##vso[task.setvariable variable=StorageAccountKey;isOutput=false;issecret=true]$($Keys[0].Value)"
            azurePowerShellVersion: LatestVersion
            pwsh: true
        - task: replacetokens@3
          displayName: 'Replace tokens manifests and values files'
          inputs:
            rootDirectory: '$(Pipeline.Workspace)/das-grafana'
            targetFiles: 'manifest/*.yml, config/**/*.yml, helm.yml'
            encoding: 'auto'
            writeBOM: true
            actionOnMissing: 'fail'
            keepToken: false
            tokenPrefix: '{{'
            tokenSuffix: '}}'
        - template: azure-pipelines-templates/deploy/step/kubernetes-create-namespace.yml@das-platform-building-blocks
          parameters:
            AksClusterName: ${{ parameters.AksClusterName }}
            AksResourceGroupName: ${{ parameters.AksResourceGroupName }}
            AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
            Namespace: $(KubernetesNamespace)
        - template: azure-pipelines-templates/deploy/step/kubernetes-create-secret.yml@das-platform-building-blocks
          parameters:
            AksClusterName: ${{ parameters.AksClusterName }}
            AksResourceGroupName: ${{ parameters.AksResourceGroupName }}
            AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
            Namespace: $(KubernetesNamespace)
            SecretArguments: --from-literal=admin-user=${{ parameters.GrafanaAdminUsername }} --from-literal=admin-password=${{ parameters.GrafanaAdminPassword }}
            SecretName: grafana-admin-user
        - template: azure-pipelines-templates/deploy/step/kubernetes-create-ingress.yml@das-platform-building-blocks
          parameters:
            AksClusterName: ${{ parameters.AksClusterName }}
            AksResourceGroupName: ${{ parameters.AksResourceGroupName }}
            AppGatewayName: ${{ parameters.AppGatewayName }}
            AppGatewayResourceGroup: ${{ parameters.AppGatewayResourceGroup }}
            AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
            IngressManifestPath: $(Pipeline.Workspace)/das-grafana/manifest/ingress.yml
            KeyVaultName: ${{ parameters.KeyVaultName }}
            Namespace: $(KubernetesNamespace)
        - template: azure-pipelines-templates/deploy/step/kubernetes-apply-manifest.yml@das-platform-building-blocks
          parameters:
            AksClusterName: ${{ parameters.AksClusterName }}
            AksResourceGroupName: ${{ parameters.AksResourceGroupName }}
            AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
            KubectlVersion: ${{ parameters.KubectlVersion }}
            ManifestFile: $(Pipeline.Workspace)/das-grafana/manifest/volume-claim.yml
            Namespace: $(KubernetesNamespace)
        - template: azure-pipelines-templates/deploy/step/kubernetes-upgrade-helmchart.yml@das-platform-building-blocks
          parameters:
            AdditionalChartRepoNameAndUrl: grafana https://grafana.github.io/helm-charts
            AksClusterName: ${{ parameters.AksClusterName }}
            AksResourceGroupName: ${{ parameters.AksResourceGroupName }}
            AzureServiceConnection: ${{ parameters.AzureServiceConnection }}
            ChartName: stable/grafana
            HelmClientVersion: ${{ parameters.HelmClientVersion }}
            HelmChartVersion: ${{ parameters.HelmChartVersion }}
            KubectlVersion: ${{ parameters.KubectlVersion }}
            Namespace: $(KubernetesNamespace)
            ReleaseName: grafana
            ValuesFile: $(Pipeline.Workspace)/das-grafana/helm.yml
