{
 "title": "Forecasting Metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "environment", "label": "Environment", "query": "${VAR_ENVIRONMENT}" }
  ]
 },
 "panels": [
  {
   "title": " Account(s) with outdated projections",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "rawSql": "select count(1)/48 as NumberOfAccounts --, DATEDIFF(DAY, ProjectionCreationDate, GETDATE()) as ProjectionAgeInDays\nfrom AccountProjection \n-- group by DATEDIFF(DAY, ProjectionCreationDate, GETDATE())\nwhere DATEDIFF(DAY, ProjectionCreationDate, GETDATE()) > 20"
    }
   ]
  },
  {
   "title": "App Service Plan",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 0, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Maximum",
        "alias": "{{metric}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/serverFarms",
        "metricName": "CpuPercentage",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-asp",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Memory Utilization",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 4, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{metric}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/serverFarms",
        "metricName": "MemoryPercentage",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-asp",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Data In",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 8, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{metric}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/serverFarms",
        "metricName": "BytesReceived",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-asp",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Data Out",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 12, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{metric}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/serverFarms",
        "metricName": "BytesSent",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-asp",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Established TCP Connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 16, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{metric}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/serverFarms",
        "metricName": "TcpEstablished",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-asp",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Disk Queue Length",
     "type": "graph",
     "gridPos": { "h": 6, "w": 4, "x": 20, "y": 5 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{metric}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/serverFarms",
        "metricName": "DiskQueueLength",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-asp",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    }
   ]
  },
  {
   "title": "Functions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "Requests",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-pld-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "Requests",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-comt-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "Requests",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-apc-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "Requests",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-lev-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "Requests",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-pay-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "Requests",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-prj-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Failed Requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Request performance", "value": "request/performanceBucket" },
         { "text": "Response code", "value": "request/resultCode" },
         { "text": "Real or synthetic traffic", "value": "operation/synthetic" },
         { "text": "Cloud role instance", "value": "cloud/roleInstance" },
         { "text": "Cloud role name", "value": "cloud/roleName" }
        ],
        "metricDefinition": "microsoft.insights/components",
        "metricName": "requests/failed",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-apc-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Request performance", "value": "request/performanceBucket" },
         { "text": "Response code", "value": "request/resultCode" },
         { "text": "Real or synthetic traffic", "value": "operation/synthetic" },
         { "text": "Cloud role instance", "value": "cloud/roleInstance" },
         { "text": "Cloud role name", "value": "cloud/roleName" }
        ],
        "metricDefinition": "microsoft.insights/components",
        "metricName": "requests/failed",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-comt-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Request performance", "value": "request/performanceBucket" },
         { "text": "Response code", "value": "request/resultCode" },
         { "text": "Real or synthetic traffic", "value": "operation/synthetic" },
         { "text": "Cloud role instance", "value": "cloud/roleInstance" },
         { "text": "Cloud role name", "value": "cloud/roleName" }
        ],
        "metricDefinition": "microsoft.insights/components",
        "metricName": "requests/failed",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-lev-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Request performance", "value": "request/performanceBucket" },
         { "text": "Response code", "value": "request/resultCode" },
         { "text": "Real or synthetic traffic", "value": "operation/synthetic" },
         { "text": "Cloud role instance", "value": "cloud/roleInstance" },
         { "text": "Cloud role name", "value": "cloud/roleName" }
        ],
        "metricDefinition": "microsoft.insights/components",
        "metricName": "requests/failed",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-pay-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Request performance", "value": "request/performanceBucket" },
         { "text": "Response code", "value": "request/resultCode" },
         { "text": "Real or synthetic traffic", "value": "operation/synthetic" },
         { "text": "Cloud role instance", "value": "cloud/roleInstance" },
         { "text": "Cloud role name", "value": "cloud/roleName" }
        ],
        "metricDefinition": "microsoft.insights/components",
        "metricName": "requests/failed",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-pld-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Count" ],
        "aggregation": "Count",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Request performance", "value": "request/performanceBucket" },
         { "text": "Response code", "value": "request/resultCode" },
         { "text": "Real or synthetic traffic", "value": "operation/synthetic" },
         { "text": "Cloud role instance", "value": "cloud/roleInstance" },
         { "text": "Cloud role name", "value": "cloud/roleName" }
        ],
        "metricDefinition": "microsoft.insights/components",
        "metricName": "requests/failed",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-prj-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "AverageResponseTime",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-pld-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "AverageResponseTime",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-comt-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "AverageResponseTime",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-apc-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "AverageResponseTime",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-lev-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "AverageResponseTime",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-pay-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      },
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "None",
         "Average",
         "Minimum",
         "Maximum",
         "Total",
         "Count"
        ],
        "aggregation": "Average",
        "alias": "{{resourcename}}",
        "dimension": "None",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Instance", "value": "Instance" }
        ],
        "metricDefinition": "Microsoft.Web/sites",
        "metricName": "AverageResponseTime",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "das-$environment-fcast-prj-fa",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    }
   ]
  },
  {
   "title": "Messages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Message Count",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Average" ],
        "aggregation": "Average",
        "alias": "{{metric}}",
        "dimension": "",
        "dimensionFilter": "*",
        "dimensions": [],
        "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
        "metricName": "QueueMessageCount",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "dastestfcaststr/default",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 hour", "value": "PT1H" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Transactions (Response Type)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 6, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Total" ],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}}",
        "dimension": "ResponseType",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Response type", "value": "ResponseType" },
         { "text": "Geo type", "value": "GeoType" },
         { "text": "API name", "value": "ApiName" },
         { "text": "Authentication", "value": "Authentication" }
        ],
        "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
        "metricName": "Transactions",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "dastestfcaststr/default",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Transactions (API)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [ "Total" ],
        "aggregation": "Total",
        "alias": "{{dimensionvalue}}",
        "dimension": "ApiName",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Response type", "value": "ResponseType" },
         { "text": "Geo type", "value": "GeoType" },
         { "text": "API name", "value": "ApiName" },
         { "text": "Authentication", "value": "Authentication" }
        ],
        "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
        "metricName": "Transactions",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "dastestfcaststr/default",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Latency (API)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "Average",
         "Minimum",
         "Maximum"
        ],
        "aggregation": "Maximum",
        "alias": "{{dimensionvalue}}",
        "dimension": "ApiName",
        "dimensionFilter": "*",
        "dimensions": [
         { "text": "None", "value": "None" },
         { "text": "Geo type", "value": "GeoType" },
         { "text": "API name", "value": "ApiName" },
         { "text": "Authentication", "value": "Authentication" }
        ],
        "metricDefinition": "Microsoft.Storage/storageAccounts/queueServices",
        "metricName": "SuccessE2ELatency",
        "resourceGroup": "das-$environment-fcast-rg",
        "resourceName": "dastestfcaststr/default",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "DTU",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 0, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "Average",
         "Maximum",
         "Minimum"
        ],
        "aggregation": "Minimum",
        "alias": "{{resourcename}}",
        "dimension": "",
        "dimensionFilter": "*",
        "dimensions": [],
        "metricDefinition": "Microsoft.Sql/servers/databases",
        "metricName": "dtu_consumption_percent",
        "resourceGroup": "das-$environment-shared-rg",
        "resourceName": "das-$environment-shared-sql/das-$environment-fcast-db",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 6, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Count"
        ],
        "aggregation": "Count",
        "alias": "{{resourcename}}",
        "dimension": "",
        "dimensionFilter": "*",
        "dimensions": [],
        "metricDefinition": "Microsoft.Sql/servers/databases",
        "metricName": "deadlock",
        "resourceGroup": "das-$environment-shared-rg",
        "resourceName": "das-$environment-shared-sql/das-$environment-fcast-db",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Successful Connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 12, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{resourcename}}",
        "dimension": "",
        "dimensionFilter": "*",
        "dimensions": [],
        "metricDefinition": "Microsoft.Sql/servers/databases",
        "metricName": "connection_successful",
        "resourceGroup": "das-$environment-shared-rg",
        "resourceName": "das-$environment-shared-sql/das-$environment-fcast-db",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    },
    {
     "title": "Failed Connection",
     "type": "graph",
     "gridPos": { "h": 7, "w": 6, "x": 18, "y": 8 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "appInsights": {
        "groupBy": "none",
        "metricName": "select",
        "rawQuery": false,
        "rawQueryString": "",
        "spliton": "",
        "timeGrainType": "auto",
        "xaxis": "timestamp",
        "yaxis": ""
       },
       "azureLogAnalytics": {
        "query": "//change this example to create your own time series query\n<table name>                                                              //the table to query (e.g. Usage, Heartbeat, Perf)\n| where $__timeFilter(TimeGenerated)                                      //this is a macro used to show the full chart’s time range, choose the datetime column here\n| summarize count() by <group by column>, bin(TimeGenerated, $__interval) //change “group by column” to a column in your table, such as “Computer”. The $__interval macro is used to auto-select the time grain. Can also use 1h, 5m etc.\n| order by TimeGenerated asc",
        "resultFormat": "time_series"
       },
       "azureMonitor": {
        "aggOptions": [
         "Total",
         "Count"
        ],
        "aggregation": "Total",
        "alias": "{{resourcename}}",
        "dimension": "",
        "dimensionFilter": "*",
        "dimensions": [],
        "metricDefinition": "Microsoft.Sql/servers/databases",
        "metricName": "connection_failed",
        "resourceGroup": "das-$environment-shared-rg",
        "resourceName": "das-$environment-shared-sql/das-$environment-fcast-db",
        "timeGrain": "auto",
        "timeGrains": [
         { "text": "auto", "value": "auto" },
         { "text": "1 minute", "value": "PT1M" },
         { "text": "5 minutes", "value": "PT5M" },
         { "text": "15 minutes", "value": "PT15M" },
         { "text": "30 minutes", "value": "PT30M" },
         { "text": "1 hour", "value": "PT1H" },
         { "text": "6 hours", "value": "PT6H" },
         { "text": "12 hours", "value": "PT12H" },
         { "text": "1 day", "value": "P1D" }
        ]
       },
       "subscription": "68208b91-0105-498e-a1bc-40d75596c01a"
      }
     ]
    }
   ]
  }
 ]
}