---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: grafana
  namespace: {{KubernetesNamespace}}
  annotations:
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: {{TlsSecretName}}
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
  - host: {{IngressHost}}
    http:
      paths:
      - path: /grafana
        backend:
          serviceName: grafana
          servicePort: 80
      - path: /grafana/*
        backend:
          serviceName: grafana
          servicePort: 80
