apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: provisioning-datasources
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: azure-file
  resources:
    requests:
      storage: 5Gi